{% set name = "google-cloud-build" %}
{% set version = "3.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-build-{{ version }}.tar.gz
  sha256: dfefcd36beb39d6131040df98b63d0e0b1e6c65af9882e3417165d986937a9d1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - proto-plus >=1.15.0

test:
  imports:
    - grpc
    - google.cloud.devtools.cloudbuild
    - google.cloud.devtools.cloudbuild_v1
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-cloudbuild
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Build API client library
  description: "Google Cloud Build API is a Google Cloud service that lets client applications create and manage builds on Google Cloud Platform. Cloud Build lets you build software quickly across all languages. Get complete control over defining custom workflows for building, testing, and deploying across multiple environments\
    \ such as VMs, serverless, Kubernetes, or Firebase.\nSee the [quick start guide](https://googleapis.dev/python/cloudbuild/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/cloudbuild/latest/index.html
  dev_url: https://github.com/googleapis/python-cloudbuild

extra:
  recipe-maintainers:
    - xylar
    - parthea
